services:
  gitlab_db:
    container_name: gitlab_db
    restart: always
    image: sameersbn/postgresql:14-20230628
    volumes:
      - /home/data/gitlab/database:/var/lib/postgresql:Z
    environment:
      - DB_USER=${DB_USER:-gitlab}
      - DB_NAME=${DB_NAME:-gitlabhq-production}
      - DB_PASS=${DB_PASS:-password}
      - DB_EXTENSION=${DB_EXTENSION:-pg_trgm,btree_gist}
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-gitlab}"]
      interval: 30s
      timeout: 10s
      retries: 5

  gitlab_redis:
    container_name: gitlab_redis
    restart: always
    image: redis:6.2.6
    command:
      - --loglevel warning
    volumes:
      - /home/data/gitlab/redis:/data:Z
    networks:
      - focela_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  gitlab:
    container_name: gitlab
    restart: always
    image: sameersbn/gitlab:17.0.1
    ports:
      - ${GITLAB_SSH_PORT:-10022}:22
    volumes:
      - /home/data/gitlab:/home/git/data:Z
    environment:
      - DEBUG=${DEBUG:-false}
      - DB_ADAPTER=${DB_ADAPTER:-postgresql}
      - DB_HOST=${DB_HOST:-gitlab_db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-gitlab}
      - DB_NAME=${DB_NAME:-gitlabhq-production}
      - DB_PASS=${DB_PASS:-password}
      - REDIS_HOST=${REDIS_HOST:-gitlab_redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - TZ=${TZ:-UTC}
      - GITLAB_TIMEZONE=${GITLAB_TIMEZONE:-UTC}
      - GITLAB_HTTPS=${GITLAB_HTTPS:-false}
      - SSL_SELF_SIGNED=${SSL_SELF_SIGNED:-false}
      - GITLAB_HOST=${GITLAB_HOST:-localhost}
      - GITLAB_PORT=${GITLAB_PORT:-10080}
      - GITLAB_SSH_PORT=${GITLAB_SSH_PORT:-10022}
      - GITLAB_RELATIVE_URL_ROOT=${GITLAB_RELATIVE_URL_ROOT}
      - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE:-long-and-random-alphanumeric-string}
      - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE:-long-and-random-alphanumeric-string}
      - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE:-long-and-random-alphanumeric-string}
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
      - GITLAB_ROOT_EMAIL=${GITLAB_ROOT_EMAIL}
      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=${GITLAB_NOTIFY_ON_BROKEN_BUILDS:-true}
      - GITLAB_NOTIFY_PUSHER=${GITLAB_NOTIFY_PUSHER:-false}
      - GITLAB_EMAIL=${GITLAB_EMAIL:-notifications@example.com}
      - GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO:-noreply@example.com}
      - GITLAB_INCOMING_EMAIL_ADDRESS=${GITLAB_INCOMING_EMAIL_ADDRESS:-reply@example.com}
      - GITLAB_BACKUP_SCHEDULE=${GITLAB_BACKUP_SCHEDULE:-daily}
      - GITLAB_BACKUP_TIME=${GITLAB_BACKUP_TIME:-01:00}
      - SMTP_ENABLED=${SMTP_ENABLED:-false}
      - SMTP_DOMAIN=${SMTP_DOMAIN:-www.example.com}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-mailer@example.com}
      - SMTP_PASS=${SMTP_PASS:-password}
      - SMTP_STARTTLS=${SMTP_STARTTLS:-true}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-login}
      - IMAP_ENABLED=${IMAP_ENABLED:-false}
      - IMAP_HOST=${IMAP_HOST:-imap.gmail.com}
      - IMAP_PORT=${IMAP_PORT:-993}
      - IMAP_USER=${IMAP_USER:-mailer@example.com}
      - IMAP_PASS=${IMAP_PASS:-password}
      - IMAP_SSL=${IMAP_SSL:-true}
      - IMAP_STARTTLS=${IMAP_STARTTLS:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    depends_on:
      - gitlab_db
      - gitlab_redis
    networks:
      - focela_network

  gitlab_runner:
    container_name: gitlab_runner
    restart: always
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
    networks:
      - focela_network

  npm_db:
    container_name: npm_db
    restart: always
    image: "jc21/mariadb-aria:latest"
    environment:
      - MYSQL_USER=${NPM_DB_USER:-npm}
      - MYSQL_DATABASE=${NPM_DB_NAME:-npm_db_name}
      - MYSQL_PASSWORD=${NPM_DB_PASSWORD:-npm_password}
      - MYSQL_ROOT_PASSWORD=${NPM_DB_ROOT_PASSWORD:-npm_root_password}
    volumes:
      - /home/data/npm/mysql:/var/lib/mysql
    networks:
      - focela_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  proxy_manager:
    container_name: proxy_manager
    restart: always
    image: "jc21/nginx-proxy-manager:2.12.1"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST=${DB_MYSQL_HOST:-npm_db}
      - DB_MYSQL_PORT=${DB_MYSQL_PORT:-3306}
      - DB_MYSQL_USER=${DB_MYSQL_USER:-npm}
      - DB_MYSQL_NAME=${DB_MYSQL_NAME:-npm_production}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD:-npm_password}
    volumes:
      - /home/data/npm/data:/data
      - /home/data/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      npm_db:
        condition: service_healthy
    networks:
      - focela_network

networks:
  focela_network:
    driver: bridge
    name: focela_network
