x-common-config: &common-config
  environment:
    TZ: ${COMMON_TZ:-Asia/Ho_Chi_Minh}
  restart: always

services:
  atlassian_db:
    <<: *common-config
    container_name: atlassian_db
    image: postgres:${ATLASSIAN_DB_VERSION:-14.10}
    environment:
      - POSTGRES_USER=${ATLASSIAN_DB_USER:-atlassian}
      - POSTGRES_PASSWORD=${ATLASSIAN_DB_PASSWORD:-password}
      - MULTIPLE_DATABASES=${ATLASSIAN_MULTIPLE_DATABASES:-db1,db2,db3}
    volumes:
      - ./data/atlassian/db:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ATLASSIAN_DB_USER:-atlassian}"]
      interval: 30s
      timeout: 10s
      retries: 5

  gitlab_db:
    <<: *common-config
    container_name: gitlab_db
    image: sameersbn/postgresql:${GITLAB_DB_VERSION:-14-20230628}
    volumes:
      - ./data/gitlab/db:/var/lib/postgresql/data:Z
    environment:
      - DB_USER=${GITLAB_DB_USER:-gitlab}
      - DB_NAME=${GITLAB_DB_NAME:-gitlabhq_production}
      - DB_PASS=${GITLAB_DB_PASS:-securepassword}
      - DB_EXTENSION=${GITLAB_DB_EXTENSION:-pg_trgm,btree_gist}
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GITLAB_DB_USER:-gitlab}"]
      interval: 30s
      timeout: 10s
      retries: 5

  confluence:
    <<: *common-config
    container_name: confluence
    image: atlassian/confluence:${CONFLUENCE_VERSION:-8.5.16}
    environment:
      - ATL_PROXY_NAME=${CONFLUENCE_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${CONFLUENCE_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${CONFLUENCE_ATL_TOMCAT_PORT:-8090}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CONFLUENCE_ATL_TOMCAT_SECURE:-false}
      - CATALINA_OPTS=${CONFLUENCE_CATALINA_OPTS:--javaagent:/opt/atlassian/confluence/atlassian-agent.jar}
    ports:
      - ${CONFLUENCE_PORT:-8090}:8090
    volumes:
      - ./data/confluence/logs:/opt/atlassian/confluence/logs
      - ./data/confluence/data:/var/atlassian/application-data/confluence
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/confluence/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  jira:
    <<: *common-config
    container_name: jira
    image: atlassian/jira-software:${JIRA_VERSION:-9.12.14}
    environment:
      - ATL_PROXY_NAME=${JIRA_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${JIRA_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${JIRA_ATL_TOMCAT_PORT:-8080}
      - ATL_TOMCAT_SCHEME=${JIRA_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${JIRA_ATL_TOMCAT_SECURE:-false}
      - CATALINA_OPTS=${JIRA_CATALINA_OPTS:--javaagent:/opt/atlassian/jira/atlassian-agent.jar}
    ports:
      - ${JIRA_PORT:-8080}:8080
    volumes:
      - ./data/jira/logs:/opt/atlassian/jira/logs
      - ./data/jira/data:/var/atlassian/application-data/jira
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  crowd:
    <<: *common-config
    container_name: crowd
    image: atlassian/crowd:${CROWD_VERSION:-6.1.1}
    environment:
      - ATL_PROXY_NAME=${CROWD_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${CROWD_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${CROWD_ATL_TOMCAT_PORT:-8095}
      - ATL_TOMCAT_SCHEME=${CROWD_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CROWD_ATL_TOMCAT_SECURE:-false}
      - CATALINA_OPTS=${CROWD_CATALINA_OPTS:--javaagent:/opt/atlassian/crowd/atlassian-agent.jar}
    ports:
      - ${CROWD_PORT:-8095}:8095
    volumes:
      - ./data/crowd/logs:/opt/atlassian/crowd/logs
      - ./data/crowd/data:/var/atlassian/application-data/crowd
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/crowd/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8095 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  gitlab_redis:
    <<: *common-config
    container_name: gitlab_redis
    image: redis:${GITLAB_REDIS_VERSION:-6.2.6}
    command: ["--loglevel", "warning"]
    volumes:
      - ./data/gitlab/redis/data:/data:Z
    networks:
      - focela_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  gitlab:
    <<: *common-config
    container_name: gitlab
    image: sameersbn/gitlab:${GITLAB_VERSION:-17.0.1}
    ports:
      - ${GITLAB_SSH_PORT:-10022}:22
      - ${GITLAB_PORT:-10080}:80
    environment:
      - DEBUG=${GITLAB_DEBUG:-false}

      - DB_ADAPTER=${GITLAB_DB_ADAPTER:-postgresql}
      - DB_HOST=${GITLAB_DB_HOST:-gitlab_db}
      - DB_PORT=${GITLAB_DB_PORT:-5432}
      - DB_USER=${GITLAB_DB_USER:-gitlab}
      - DB_NAME=${GITLAB_DB_NAME:-gitlabhq_production}
      - DB_PASS=${GITLAB_DB_PASS:-securepassword}

      - REDIS_HOST=${GITLAB_REDIS_HOST:-gitlab_redis}
      - REDIS_PORT=${GITLAB_REDIS_PORT:-6379}

      - GITLAB_TIMEZONE=${GITLAB_TIMEZONE:-Asia/Ho_Chi_Minh}

      - GITLAB_HTTPS=${GITLAB_HTTPS:-false}
      - SSL_SELF_SIGNED=${GITLAB_SSL_SELF_SIGNED:-false}

      - GITLAB_HOST=${GITLAB_HOST:-localhost}
      - GITLAB_PORT=${GITLAB_PORT:-10080}
      - GITLAB_SSH_PORT=${GITLAB_SSH_PORT:-10022}
      - GITLAB_RELATIVE_URL_ROOT=${GITLAB_RELATIVE_URL_ROOT}
      - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE:-long-and-random-alphanumeric-string}
      - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE:-long-and-random-alphanumeric-string}
      - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE:-long-and-random-alphanumeric-string}

      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
      - GITLAB_ROOT_EMAIL=${GITLAB_ROOT_EMAIL}

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=${GITLAB_NOTIFY_ON_BROKEN_BUILDS:-true}
      - GITLAB_NOTIFY_PUSHER=${GITLAB_NOTIFY_PUSHER:-false}

      - GITLAB_EMAIL=${GITLAB_EMAIL:-notifications@example.com}
      - GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO:-noreply@example.com}
      - GITLAB_INCOMING_EMAIL_ADDRESS=${GITLAB_INCOMING_EMAIL_ADDRESS:-reply@example.com}

      - GITLAB_BACKUP_SCHEDULE=${GITLAB_BACKUP_SCHEDULE:-daily}
      - GITLAB_BACKUP_TIME=${GITLAB_BACKUP_TIME:-01:00}

      - SMTP_ENABLED=${GITLAB_SMTP_ENABLED:-false}
      - SMTP_DOMAIN=${GITLAB_SMTP_DOMAIN:-www.example.com}
      - SMTP_HOST=${GITLAB_SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${GITLAB_SMTP_PORT:-587}
      - SMTP_USER=${GITLAB_SMTP_USER:-mailer@example.com}
      - SMTP_PASS=${GITLAB_SMTP_PASS:-password}
      - SMTP_STARTTLS=${GITLAB_SMTP_STARTTLS:-true}
      - SMTP_AUTHENTICATION=${GITLAB_SMTP_AUTHENTICATION:-login}

      - IMAP_ENABLED=${GITLAB_IMAP_ENABLED:-false}
      - IMAP_HOST=${GITLAB_IMAP_HOST:-imap.gmail.com}
      - IMAP_PORT=${GITLAB_IMAP_PORT:-993}
      - IMAP_USER=${GITLAB_IMAP_USER:-mailer@example.com}
      - IMAP_PASS=${GITLAB_IMAP_PASS:-password}
      - IMAP_SSL=${GITLAB_IMAP_SSL:-true}
      - IMAP_STARTTLS=${GITLAB_IMAP_STARTTLS:-false}

      - OAUTH_ENABLED=${GITLAB_OAUTH_ENABLED:-false}
      - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=${GITLAB_OAUTH_AUTO_SIGN_IN_WITH_PROVIDER}
      - OAUTH_ALLOW_SSO=${GITLAB_OAUTH_ALLOW_SSO}
      - OAUTH_BLOCK_AUTO_CREATED_USERS=${GITLAB_OAUTH_BLOCK_AUTO_CREATED_USERS:-true}
      - OAUTH_AUTO_LINK_LDAP_USER=${GITLAB_OAUTH_AUTO_LINK_LDAP_USER:-false}
      - OAUTH_AUTO_LINK_SAML_USER=${GITLAB_OAUTH_AUTO_LINK_SAML_USER:-false}
      - OAUTH_EXTERNAL_PROVIDERS=${GITLAB_OAUTH_EXTERNAL_PROVIDERS}

      - OAUTH_CAS3_LABEL=${GITLAB_OAUTH_CAS3_LABEL:-cas3}
      - OAUTH_CAS3_SERVER=${GITLAB_OAUTH_CAS3_SERVER}
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=${GITLAB_OAUTH_CAS3_DISABLE_SSL_VERIFICATION:-false}
      - OAUTH_CAS3_LOGIN_URL=${GITLAB_OAUTH_CAS3_LOGIN_URL:-/cas/login}
      - OAUTH_CAS3_VALIDATE_URL=${GITLAB_OAUTH_CAS3_VALIDATE_URL:-/cas/p3/serviceValidate}
      - OAUTH_CAS3_LOGOUT_URL=${GITLAB_OAUTH_CAS3_LOGOUT_URL:-/cas/logout}

      - OAUTH_GOOGLE_API_KEY=${GITLAB_OAUTH_GOOGLE_API_KEY}
      - OAUTH_GOOGLE_APP_SECRET=${GITLAB_OAUTH_GOOGLE_APP_SECRET}
      - OAUTH_GOOGLE_RESTRICT_DOMAIN=${GITLAB_OAUTH_GOOGLE_RESTRICT_DOMAIN}

      - OAUTH_FACEBOOK_API_KEY=${GITLAB_OAUTH_FACEBOOK_API_KEY}
      - OAUTH_FACEBOOK_APP_SECRET=${GITLAB_OAUTH_FACEBOOK_APP_SECRET}

      - OAUTH_TWITTER_API_KEY=${GITLAB_OAUTH_TWITTER_API_KEY}
      - OAUTH_TWITTER_APP_SECRET=${GITLAB_OAUTH_TWITTER_APP_SECRET}

      - OAUTH_GITHUB_API_KEY=${GITLAB_OAUTH_GITHUB_API_KEY}
      - OAUTH_GITHUB_APP_SECRET=${GITLAB_OAUTH_GITHUB_APP_SECRET}
      - OAUTH_GITHUB_URL=${GITLAB_OAUTH_GITHUB_URL}
      - OAUTH_GITHUB_VERIFY_SSL=${GITLAB_OAUTH_GITHUB_VERIFY_SSL}

      - OAUTH_GITLAB_API_KEY=${GITLAB_OAUTH_GITLAB_API_KEY}
      - OAUTH_GITLAB_APP_SECRET=${GITLAB_OAUTH_GITLAB_APP_SECRET}

      - OAUTH_BITBUCKET_API_KEY=${GITLAB_OAUTH_BITBUCKET_API_KEY}
      - OAUTH_BITBUCKET_APP_SECRET=${GITLAB_OAUTH_BITBUCKET_APP_SECRET}
      - OAUTH_BITBUCKET_URL=${GITLAB_OAUTH_BITBUCKET_URL}

      - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=${GITLAB_OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL}
      - OAUTH_SAML_IDP_CERT_FINGERPRINT=${GITLAB_OAUTH_SAML_IDP_CERT_FINGERPRINT}
      - OAUTH_SAML_IDP_SSO_TARGET_URL=${GITLAB_OAUTH_SAML_IDP_SSO_TARGET_URL}
      - OAUTH_SAML_ISSUER=${GITLAB_OAUTH_SAML_ISSUER}
      - OAUTH_SAML_LABEL=${GITLAB_OAUTH_SAML_LABEL:-"Our SAML Provider"}
      - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=${GITLAB_OAUTH_SAML_NAME_IDENTIFIER_FORMAT:-urn:oasis:names:tc:SAML:2.0:nameid-format:transient}
      - OAUTH_SAML_GROUPS_ATTRIBUTE=${GITLAB_OAUTH_SAML_GROUPS_ATTRIBUTE}
      - OAUTH_SAML_EXTERNAL_GROUPS=${GITLAB_OAUTH_SAML_EXTERNAL_GROUPS}
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=${GITLAB_OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL}
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=${GITLAB_OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME}
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_USERNAME=${GITLAB_OAUTH_SAML_ATTRIBUTE_STATEMENTS_USERNAME}
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=${GITLAB_OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME}
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=${GITLAB_OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME}

      - OAUTH_CROWD_SERVER_URL=${GITLAB_OAUTH_CROWD_SERVER_URL}
      - OAUTH_CROWD_APP_NAME=${GITLAB_OAUTH_CROWD_APP_NAME}
      - OAUTH_CROWD_APP_PASSWORD=${GITLAB_OAUTH_CROWD_APP_PASSWORD}

      - OAUTH_AUTH0_CLIENT_ID=${GITLAB_OAUTH_AUTH0_CLIENT_ID}
      - OAUTH_AUTH0_CLIENT_SECRET=${GITLAB_OAUTH_AUTH0_CLIENT_SECRET}
      - OAUTH_AUTH0_DOMAIN=${GITLAB_OAUTH_AUTH0_DOMAIN}
      - OAUTH_AUTH0_SCOPE=${GITLAB_OAUTH_AUTH0_SCOPE}

      - OAUTH_AZURE_API_KEY=${GITLAB_OAUTH_AZURE_API_KEY}
      - OAUTH_AZURE_API_SECRET=${GITLAB_OAUTH_AZURE_API_SECRET}
      - OAUTH_AZURE_TENANT_ID=${GITLAB_OAUTH_AZURE_TENANT_ID}
    volumes:
      - ./data/gitlab/data:/home/git/data:Z
    depends_on:
      - gitlab_db
      - gitlab_redis
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m

networks:
  focela_network:
    driver: bridge
