x-common-config: &common-config
  environment:
    TZ: ${COMMON_TZ:-Asia/Ho_Chi_Minh}
  restart: always

services:
  atlassian_db:
    <<: *common-config
    container_name: atlassian_db
    image: postgres:${ATLASSIAN_DB_VERSION:-14.10}
    environment:
      - POSTGRES_USER=${ATLASSIAN_DB_USER:-atlassian}
      - POSTGRES_PASSWORD=${ATLASSIAN_DB_PASSWORD:-password}
      - MULTIPLE_DATABASES=${ATLASSIAN_MULTIPLE_DATABASES:-db1,db2,db3}
    volumes:
      - ./data/atlassian/db:/var/lib/postgresql/data
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ATLASSIAN_DB_USER:-atlassian}"]
      interval: 30s
      timeout: 10s
      retries: 5

  confluence:
    <<: *common-config
    container_name: confluence
    image: atlassian/confluence:${CONFLUENCE_VERSION:-8.5.16}
    environment:
      - ATL_PROXY_NAME=${CONFLUENCE_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${CONFLUENCE_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${CONFLUENCE_ATL_TOMCAT_PORT:-8090}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CONFLUENCE_ATL_TOMCAT_SECURE:-false}
      - CATALINA_OPTS=${CONFLUENCE_CATALINA_OPTS:--javaagent:/opt/atlassian/confluence/atlassian-agent.jar}
    ports:
      - ${CONFLUENCE_PORT:-8090}:8090
    volumes:
      - ./data/confluence/logs:/opt/atlassian/confluence/logs
      - ./data/confluence/data:/var/atlassian/application-data/confluence
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/confluence/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  jira:
    <<: *common-config
    container_name: jira
    image: atlassian/jira-software:${JIRA_VERSION:-9.12.14}
    environment:
      - ATL_PROXY_NAME=${JIRA_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${JIRA_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${JIRA_ATL_TOMCAT_PORT:-8080}
      - ATL_TOMCAT_SCHEME=${JIRA_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${JIRA_ATL_TOMCAT_SECURE:-false}
    ports:
      - ${JIRA_PORT:-8080}:8080
    volumes:
      - ./data/jira/logs:/opt/atlassian/jira/logs
      - ./data/jira/data:/var/atlassian/application-data/jira
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  crowd:
    <<: *common-config
    container_name: crowd
    image: atlassian/crowd:${CROWD_VERSION:-6.1.1}
    environment:
      - ATL_PROXY_NAME=${CROWD_ATL_PROXY_NAME:-localhost}
      - ATL_PROXY_PORT=${CROWD_ATL_PROXY_PORT:-443}
      - ATL_TOMCAT_PORT=${CROWD_ATL_TOMCAT_PORT:-8095}
      - ATL_TOMCAT_SCHEME=${CROWD_ATL_TOMCAT_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CROWD_ATL_TOMCAT_SECURE:-false}
      - CATALINA_OPTS=${CROWD_CATALINA_OPTS:--javaagent:/opt/atlassian/crowd/atlassian-agent.jar}
    ports:
      - ${CROWD_PORT:-8095}:8095
    volumes:
      - ./data/crowd/logs:/opt/atlassian/crowd/logs
      - ./data/crowd/data:/var/atlassian/application-data/crowd
      - ./data/atlassian/atlassian-agent.jar:/opt/atlassian/crowd/atlassian-agent.jar
    depends_on:
      - atlassian_db
    networks:
      - focela_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8095 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  focela_network:
    driver: bridge
