services:
  gitlab-db:
    container_name: gitlab-db
    restart: always
    image: sameersbn/postgresql:14-20230628
    env_file:
      - ./gitlab.env
    volumes:
      - /home/data/gitlab/postgresql:/var/lib/postgresql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
